version: "3"

services:
   playwright:
      image: mcr.microsoft.com/playwright/java:focal
      container_name: container.secure.efax.com
      working_dir: /tmp/pw-java
      volumes:
         - .:/tmp/pw-java
      command: sh -c "mvn clean compile test -ntp -e -P qa -D uploadResults=false -D skipTests=false -D testRunId=11111 -D webbrowser=chrome -D headless=true -D suiteXmlFiles=secure.fax.debug.xml -D oracle.jdbc.timezoneAsRegion=false"
      extra_hosts:
         - "qa.efax.es:10.160.90.62"
         - "qa.efax.de:10.160.90.61"
         - "qa.efax.fr:10.160.90.60"
         - "qa.efax.nl:10.160.90.63"
         - "qa.it.efax.com:10.160.90.69"
         - "qa.efax.co.jp:10.160.90.70"
         - "qa.efax.com.au:10.160.90.58"
         - "qa.efax.ca:10.160.90.84"
         - "qa.mbox.com.au:10.160.90.73"
         - "qa.jfax.com:10.160.90.100"
         - "qa.myaccount.myhealthinbox.com:10.160.90.192"
         - "qa.efaxcorporate.com:10.160.90.170"
         - "qa.central.myfax.com:10.160.90.79"
         - "qawww.efax.com:10.160.90.149"
         - "qamyaccount.metrofax.com:10.160.90.55"
         - "qamyaccount.jconnect.com:10.160.90.68"
         - "qa.efax.co.uk:10.160.90.57"